apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: homepage
stringData:
    auth-secret: ENC[AES256_GCM,data:zHHNGYXFQxsK271JlWo+2ZAmr9TNMbYfHNArE/qflW5nI0pR5sJ53IngEkw=,iv:wmdUC40y0rc4ehb78XZUjHtO3oaZdXcSCEG1RabHmsw=,tag:pmJ6JmIc60yWa5gx4yNKAg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSVQ3blFmLzVodnRtaEtl
            QU1GY2tHM3ZqTENHK0xWTkZ6bXlpSVRFRWpvCmxKM3BnclQySkpWWEN4SWJoajVn
            UGRFOFB4ZkxuWm5iWkRZemlabUpFMG8KLS0tIFJNWFBoT3BZZ20zVWsxQU1McFlL
            aHAzamJPNkcxTlYwYlRTV2JXN2srOEUKRQvzDOlJfMQhpUV/GgdkR52juGq8h1Xv
            KOfYL1WpGw7W3gXK65I/xoL97XHCIiCZ+Pr0zT0JzucJVnz5i1O1xA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tygf3cppgemsa5h93gwyk2ucg55n48ernr8afvpul6uy7pek7sjscavun5
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-09-01T01:25:50Z"
    mac: ENC[AES256_GCM,data:ppdkZEIfHQX0xFk8CA5y8CkszjsrBaWaJxk9Okl+os9e+AHR8Yw1+bnGhJFbjclcweWiW9aBIBbALFA8ReHTzSN8Ub2XNO4/Zil3J9E3H+Gs7D5QXdWbg7YFSVAwqonccdL4y97teVugQGTzoUncQhsGnCkz8JDjOTzLFTnbivs=,iv:rjeyCT1tP/7gG6BHRMViXeHaQhybpgfzZAB9m7qY4ic=,tag:IxJJAEVbAwMGBQI7xuDoMQ==,type:str]
    version: 3.13.3
