apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - network-policies.yaml
  - config.yaml
  - homepage.yaml
  - homepage-oidc-config.yaml

generators:
  - ksops-generator.yaml
