apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-oauth2-proxy-cookie-secret
    namespace: arr-downloader
stringData:
    cookie-secret: ENC[AES256_GCM,data:YZex1oigUg0vVkb0fVlOJPbwlAHhiWgK0ffvYk60sNE=,iv:nT83fNqtVS54bcnuhmgBlRhW5CR4EsrwQN8KMGGzg/M=,tag:n5u99BniItSVoPLGjyLV6A==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRXNWUmdpczhJS1Z1N2JQ
            KzlhU3pWMjAyKzc3ZDBPd0RrZ2ZmaG1NYWpBCjZiWHVvUThqT2ppVjZlYWJ3SmJ1
            WkxTUWJEanRLWStmQU5IWGxKdUtBTVEKLS0tIEtZdTkzMTQ5V2Rkd2RCbHJ6dTJK
            QkQ5bVc4SGNOdk55Q2pQOHdOYXlwcm8K08siYplyYdFhh4SoGIUOrwOFEdHP85lJ
            0P8jlQx5gPWQ4n7ZUNl01GZPfsMlEYvn83rg0VYNCiHpGV/Y3O2qPg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tygf3cppgemsa5h93gwyk2ucg55n48ernr8afvpul6uy7pek7sjscavun5
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-09-11T18:06:20Z"
    mac: ENC[AES256_GCM,data:8FKwgexdrvtlz/UJbX9C3uhsG/z+e21qEAJVi7KF+gs7ByOaM/fzngOkcF8AY0p48bEkB82ePRyc3LMaQbdfaz+DlorZs//M8Muv5h/R+/c75K0IbElFebGYqXOF1SZkN16mZqJDuOzgyQ2UrIt6uqhWBanN744zE83M8WK25jw=,iv:EiLPyX+cB83AZAYNetpuLVutRZqnhoJj/dKpjZbI5Rs=,tag:3B6no9YwnF1xF7i+Rvf2ag==,type:str]
    version: 3.13.3
