apiVersion: v1
kind: Secret
metadata:
    name: changedetection-oauth2-proxy-credentials
    namespace: changedetection
stringData:
    client-id: ENC[AES256_GCM,data:XxOOuEfM6+sg3Vhd05kYlvqMiAVC4eTzIzrq4A==,iv:kzcSLtRjEK0pOjRUqZf8ZUjdpvaY5ft2j19wzsrsbAk=,tag:lPT0Z2eJqOZTO0qzjoNHnw==,type:str]
    client-secret: ENC[AES256_GCM,data:92WFtUFhW+0RiUg+GUTeVGCembVsh0yb7rEUdLwAOqk=,iv:rj2I3WJsfcuY8HDFPDlU7GLbb1s33K5nt8vHhSOJnHA=,tag:9Wi5C6NX8xtotmsJvGRtqg==,type:str]
    cookie-secret: ENC[AES256_GCM,data:N5+HNU0p1oZPHKjhQUpbrYNkgADRCfKzWVh9lUgAzBo=,iv:LSV5CWZVFUsxCIk3UkOzAq3PjqPhV1ScizNszoDjhog=,tag:uRiRTqe5u9oLVHD14Ap7Dg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYldvZFpZQmVJTFE5dGU5
            OG1XZnJBT1hVZDFrczdtb0RadHE5eldOVkNBCmpBTFFkTUw0ZEthZ1FMbDVmeGFx
            M2pNd1NVZWcwWjh1c0tCaFk0VlVuN1UKLS0tIEtDMU00RWZXNUtGS3ByTW9mWWRa
            OGNUbU5vMDZKYncyUnRva2dtY01mbm8KcaxUGzfOFPDUYb3bh+v0zRz39ElqRw68
            9fiaMnH2Cy6TCVPO5zf7JZ/11k+wduWXb41QMdP1sam19w1i7BrHWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tygf3cppgemsa5h93gwyk2ucg55n48ernr8afvpul6uy7pek7sjscavun5
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-08-29T16:07:51Z"
    mac: ENC[AES256_GCM,data:kdRG0lAaM+IlFimkfrk72a0YStQcYzDd1UZ7cNdlCB616wL154WZ8nlde+tJw9UPznB7KufG43Vi5Q3UB88vYhhGtRD4AN8H9K209g9lKJHiOUS2jHaOQkvifBiBkjs5lOYDE9xWBos/wE0yIF7epBdrXK4EW28mQWCtTu+dhUk=,iv:80FUpB4z2FtoOuqdCl7AVD3hVEAlcR3FlYRwpLFaRv8=,tag:Xw0H+chuoKUFpQpE8aLqzw==,type:str]
    version: 3.13.3
