apiVersion: v1
kind: Secret
metadata:
    name: homebox-config
    namespace: inventory
stringData:
    api-key-pepper: ENC[AES256_GCM,data:sdDVf0MqM/LR1nkyqx8TaH9zDds9XvqDYvpN5wuT92nu/aFFSVV6uspKdYo5cOPUzx2O0JtIiUepQZB29CGJ,iv:aI+0FsKWvPsHwZyXn8Ny+lmPSa+IpbGQMUbjcVNY+Vc=,tag:jxvfIdUsu0m/ieB6KArTMA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETTlJcHp6WExoR0Zya0to
            M081SzhabzRLN0dmYUFmV29aRTlZVWZ2M3dnCllJRzZlUEVVZDdnTVdDVTBpWFFO
            NnlZbDc1V3l4MGpWK0t3SzJRWVFkM2cKLS0tIEV5RVBreUhxeG91cDF3Tmd6TXIz
            YVZNbGluOEx3Y1E1eXlsUUNmWEJvY00Kn9c824HWTSX5l59EoJjaCBtsBi8L4FUF
            qyqbJuz3IMTob9gT1rQMrnoAa3aPk3BB67G+NOxGpNoj1J5scumgDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tygf3cppgemsa5h93gwyk2ucg55n48ernr8afvpul6uy7pek7sjscavun5
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-08-29T21:22:55Z"
    mac: ENC[AES256_GCM,data:ThrDK8tVDE1z8MXAmHI1rutRpnsR4SrL5feVXgdlq4a/O5KJXxK8ElWMVRO4GTXmmsyosOJ76DzfFFyoO3JxrvQwYk9mGp1E5UwjmmZS6DTb76gbN3b5w+Td5Ojie2AyyBfvoPMkuiuGw9ziSUgQgqqj112B7QDO00ArsMxDwkQ=,iv:DGhlpqZJliKs/pxJYEKei/eD+FhVPT9S0ajiF8Gn3/g=,tag:Zq6Ou/5jagxg3E3doIX+QA==,type:str]
    version: 3.13.3
