apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: youtube-archiver-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./pinchflat-basic-auth.enc.yaml
