apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - config-pvc.yaml
  - downloads-pvc.yaml
  - network-policies.yaml
  - pinchflat.yaml

generators:
  - ksops-generator.yaml
