apiVersion: v1
kind: Secret
metadata:
    name: pinchflat-basic-auth
    namespace: youtube-archiver
stringData:
    username: ENC[AES256_GCM,data:T74wTSQ=,iv:DajptQEh9mXgliMGTuETTm2zRgwefZVhigh0rFxlLrs=,tag:UvTCAZqoDvbSxrTS+1ji/w==,type:str]
    password: ENC[AES256_GCM,data:PHIUxBQpQl/ypnEhomZ/vw6uUSN66Rpe,iv:w5/surR/+xRU4G/scigHqEDZQp1zoq6MlOZ0vDYMq5A=,tag:kNFYLPC8eEhC5mp6pY1y9g==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuK0ZTSWxZOVlFazk1N2ZV
            bzRUU3dqOGNnT2lvV1hCSzhTWW44dUZDZEU4Cnh3blVlTFpGeE9ab0hKdkJZdWxy
            d2VyNCtEWnVkU0lPbjBTZkx4empWOWMKLS0tIGNoOXBlbCtNVHgvTVVucSs3bVhH
            NlNTeTFteDFhVEtLdzUvSkxUQlhvUmMKH3Dej+Nj3Mous+ewPhmYx4jCkiA8eHWC
            5ZYXwqlzXLdWahyqbkT3Ck31qgSQUbkOStd+kmoM5bvsx7k3cp98Tw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tygf3cppgemsa5h93gwyk2ucg55n48ernr8afvpul6uy7pek7sjscavun5
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-09-01T13:07:27Z"
    mac: ENC[AES256_GCM,data:ZFeyuRyXTqf42EF3at+4hqutak+aJDoAcIJItO6sqyd5hIODjDOdkvggap+An9nKupz5i5rzfTjoWVHu7HM0YoNcTHnZ0Wy5wTlI5GKFOyRMTjVup2kMMpHywLPQdJbGtjn7K9nlMOcn0jXlZ/w8eBtG/CyIGnNrFsO+JEB9KtA=,iv:UgqU9QTWz5du9FsehOaiJD5jEwnNHbr5CDcbQrJT5Mc=,tag:zdGnBpcssKOeZHjxFLwP7Q==,type:str]
    version: 3.13.3
