apiVersion: v1
kind: Secret
metadata:
    name: pinchflat-oauth2-proxy-cookie-secret
    namespace: youtube-archiver
stringData:
    cookie-secret: ENC[AES256_GCM,data:Z4PpLPcCaSv5YN8+z8E9FKQ4o0SE4p6jD3RXPtlbboQ=,iv:vxAesoVxTtwEZFjtODjLZ/wg4qgngLAFiMYTrVJ79eI=,tag:c8lu1JNIvdF+v54Bx4ixcA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cFl3MmR2bnZLVXVaU3RE
            eE16UkErSFRmZUhzY2cvWC9CbFJuQXJzM0JvCmtrUDVLL0I3cU9Pd1kzQWJaeG81
            QnJJUXNGT3g4K0lSVFB4WWx0cUszYzgKLS0tIGFTLzRNME96clpuM0d1UHRpTHA4
            K1JPTmsyeWtmQWh0TzFvRlE4RDg5ZHcK5d+lqvfkLC2UXx7sEwXnsddpnLrNObIW
            fbbgc3utmZZzAjZsHG6NZegd8qDGHS8Fq3mGGH7AxW5bW388ADlZ9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tygf3cppgemsa5h93gwyk2ucg55n48ernr8afvpul6uy7pek7sjscavun5
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-09-01T13:24:50Z"
    mac: ENC[AES256_GCM,data:eMGgBHzFHL5ZBp66WPhzqqvZk/GaurUjL6UIjaJN2DB0QmJvsOJP5vP2JZtIEAuXH/zLp+OIXVhYgzLBHzS6znvTbJzLLSr+qFIBvtDRkZ7VgiregzGYEMnuBaD44MuOtjcq3N8QjhaGQcnDeIuKkpIdcTGPc/FL1lGYOZY6z+Q=,iv:3UwiBHY8k9qQapH7LTzX1MDhFhKIdcVRHhDWAqmtFTc=,tag:/wk/WP4oyEhlzzu9UEtFwQ==,type:str]
    version: 3.13.3
