apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - env-values.yaml

replacements:
  - source:
      kind: ConfigMap
      name: env-values
      fieldPath: data.app-hostname
    targets:
      - select:
          kind: Ingress
          name: synapse
        fieldPaths:
          - spec.rules.0.host
          - spec.tls.0.hosts.0
      - select:
          kind: ConfigMap
          name: synapse-config
        fieldPaths:
          - data.homeserver\.yaml
        options:
          delimiter: "/"
          index: 2
      - select:
          kind: ConfigMap
          name: matrix-wellknown
        fieldPaths:
          - data.matrix-client\.json
        options:
          delimiter: "/"
          index: 2
  - source:
      kind: ConfigMap
      name: env-values
      fieldPath: data.element-hostname
    targets:
      - select:
          kind: Ingress
          name: element-web
        fieldPaths:
          - spec.rules.0.host
          - spec.tls.0.hosts.0
  - source:
      kind: ConfigMap
      name: env-values
      fieldPath: data.domain-name
    targets:
      - select:
          kind: Ingress
          name: matrix-wellknown
        fieldPaths:
          - spec.rules.0.host
          - spec.tls.0.hosts.0
      - select:
          kind: ConfigMap
          name: synapse-config
        fieldPaths:
          - data.homeserver\.yaml
        options:
          delimiter: '"'
          index: 1
      - select:
          kind: ConfigMap
          name: element-web-config
        fieldPaths:
          - data.config\.json
        options:
          delimiter: '"'
          index: 3
  - source:
      kind: ConfigMap
      name: env-values
      fieldPath: data.app-hostname-with-port
    targets:
      - select:
          kind: ConfigMap
          name: matrix-wellknown
        fieldPaths:
          - data.matrix-server\.json
        options:
          delimiter: '"'
          index: 3
  - source:
      kind: ConfigMap
      name: env-values
      fieldPath: data.matrix-calls-hostname
    targets:
      - select:
          kind: ConfigMap
          name: synapse-config
        fieldPaths:
          - data.homeserver\.yaml
        options:
          delimiter: "/"
          index: 5
      - select:
          kind: ConfigMap
          name: matrix-wellknown
        fieldPaths:
          - data.matrix-client\.json
        options:
          delimiter: "/"
          index: 5
  - source:
      kind: ConfigMap
      name: env-values
      fieldPath: data.storage-class-ceph
    targets:
      - select:
          kind: PersistentVolumeClaim
          name: matrix-signing-key
        fieldPaths:
          - spec.storageClassName
      - select:
          kind: StatefulSet
        fieldPaths:
          - spec.volumeClaimTemplates.0.spec.storageClassName
  - source:
      kind: ConfigMap
      name: env-values
      fieldPath: data.storage-class-nfs
    targets:
      - select:
          kind: PersistentVolumeClaim
          name: matrix-media
        fieldPaths:
          - spec.storageClassName
