apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - livekit.yaml
  - lk-jwt-service.yaml
  - ingress.yaml
  - network-policies.yaml

generators:
  - ksops-generator.yaml
