apiVersion: v1
kind: Secret
metadata:
    name: livekit-config
    namespace: matrix-livekit
stringData:
    livekit.yaml: ENC[AES256_GCM,data:p1deDHPa/3yTLblTntCyu7knKqQs08pw+kJw6+zfrrTePCJ+RMFnpr3qz1/jywu5txCl0J/rNVbJ3D1fgjZ6qE088K/9KdOw9CDzaTLzwbpqelzvuXT3FTRmJ9DvUbOcZfV/SINBqZdwGS/dgW8F++QQBrehsVuvXRrCs8GW9jqgsShd+1MTpO9W+e+gmb1k8R0ZRGhVz57XReStkpphpkEex970,iv:xRni5yDnAwueLt/qyQr/PI9chWpnW2SLDS4W41V4mwQ=,tag:4EhUe4LsM6NDmmRWdlPIpQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYS0NOR09kaDV3UktZNCsr
            TlJrbnVxMzR0NTBjK2lQT3ZUVlB2bjBBNEU4ClFLUGJTN3JxR2MzQVhJaytaUHlT
            RGs5eU5OK3ZvTXJuUTZIb2JzdU00bTQKLS0tIEEvaHc1cTFHTkRURzFjV3FlMHA3
            MUYxSXVuZitPOXZXR0E1TzFBWXVmL2cKELSAnKICYvBEjw0oXXl9TMsK8w1iSEdD
            J6p7/DB6T31/uadgp8SYy9r4y42hRkn49M/Kc4nxTFXffsaPEsPwVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tygf3cppgemsa5h93gwyk2ucg55n48ernr8afvpul6uy7pek7sjscavun5
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-09-02T18:27:09Z"
    mac: ENC[AES256_GCM,data:rgQ19Ea4NNdY4OXRowJzXcFqyr+2lTVUg7qDcs2b8L/LrqG8uF1dhN2YATuwbc8edoVbnMi+AwQIky5wliErXccRuEKSar8+2aBgh1zPH+8ybC9p7yreMwLwq/vt/CWCEZ5Vs3kDSxxjjd+xFye/Ki8e4EJjUd1XBh7c8CIUErw=,iv:KIzD3eyfZlJosENgIF7Uei+g3hzvzLcewRChbhrghyU=,tag:sHpGs/W1IPhuBhkC6/kWVQ==,type:str]
    version: 3.13.3
