apiVersion: v1
kind: Secret
metadata:
    name: livekit-config
    namespace: matrix-livekit
stringData:
    livekit.yaml: ENC[AES256_GCM,data:6OF3rArPlI33isJgXUnss6QAHZWFgQz8iDN3BjNc53unZNAMItOJD5P67SWXO893jkF5xJC0RCQewWiJuB0vunvR+cEkrPnGQHRJdhULjH0b6+j18vPC/sO4LMzR2k6BOGW3i4VgkVpResjrmAVDbMWsScj7ggAwR5vZOHEmR1Y7k9DF,iv:kYQC+OWwMBLYq7MWPJRV8WBqgbMWkvDrXWi9gYaRKCs=,tag:gdy6Km+J17gH6oVy7TTN3A==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQms3d1Q2dWtNdG5nT2RJ
            dnpZR2w3bERhODlOV2NTZlBnQWkwNlNmOUdJCk5CWk1VOFRYS2RzaGI5TDVpa2Zv
            RTBRRkZjWnQ4L05HN2xsMVppZHhNbncKLS0tIG9Lak82RENvd0pucEx0Tmx5cVhj
            N3RKcXlyMkxla1JqZzg0b0VKVkxXUFUKa1fd6ZReuZAPyH/i+dMdxzjZOcR+r7gV
            6MbQpBZkY3Qac4Q0Jn2r/5EY6/lQWP93OrT3/6lT0i8QKvEtojwkGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tygf3cppgemsa5h93gwyk2ucg55n48ernr8afvpul6uy7pek7sjscavun5
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-09-02T03:25:42Z"
    mac: ENC[AES256_GCM,data:YwdfLhMYa4abvEVwLGeA202TWBExDdXty37vOGyrLsp4dFENVI9A2x4mx90/gM1sV/6gUrIMPyF4xLyr9mUAR8/PnmHFlFPnf66BTOFvvlCd2kgBb+baISHf02O3M525kNCaIG6JtTHIfar8nNnvZtLXMLavbEqb1aybX34VbUU=,iv:2gnnY74SqgwAPcEglvSmpKsgtBipyBiP0P/FEtwvn+U=,tag:VxwAWGfjkwcVGfy1UBazSg==,type:str]
    version: 3.13.3
