apiVersion: v1
kind: Secret
metadata:
    name: lk-jwt-credentials
    namespace: matrix-livekit
stringData:
    livekit-key: ENC[AES256_GCM,data:/sjFSsSlHHHLAcop3jzjV7Oz,iv:Xjo+v4UZGdC4zENpEa6pTsHpXtHEY/b+GkUCVcmMv2I=,tag:vnx+mCeuBJax45R0svcBpw==,type:str]
    livekit-secret: ENC[AES256_GCM,data:w6phcTqq0atGx483zGgqlMDmwopfnek562HBD8e/p3qpu0Mq+UaqfO9l90s=,iv:uGn4B4yb8mAyU2hMRoIMdkmkgHc3bSIV6zzQMVk08gQ=,tag:NHwZPljKYzSAA7R0jNA2Lg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsamVSMThkcys4M2FOZkZ1
            M1hQWS9CVTU0dllZNnM0ano0YnhPUk5MekRnClE2eHlNRDR6dnhyYWZncVVoNndF
            K1NEVkxOL2svUEI3bmVDS2hTWU8xbnMKLS0tIG1ySS95ek0zOGZFNlJZOWFHdFRB
            MVpjYXAzQllweGhjb2tJem9oM1ZFN2sKgSyxQB7t8FeWnvZshOj9vaK2Cy1EgI9L
            0+gK2VX0WUm3ltWJ97VrGSIdRaHX8kbh62NNHgJgy7TVRFeyzA/t3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tygf3cppgemsa5h93gwyk2ucg55n48ernr8afvpul6uy7pek7sjscavun5
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-09-02T03:25:42Z"
    mac: ENC[AES256_GCM,data:fophUR4KdC8Gy0fJqJVEvnXmXx1CJivLnI1ia2DNPLvsNDuKAlNpAYSwOT/lAhDiO9qouHti+Q97kNSYz4wHrjam2tA9SzmWBwgdqh8wVr/mfNhkbDgXrAJZ2ULcJmadQF0yGRCMV/8A8gO93KlF4y9yyq9ekttbIJEb0vKTQuE=,iv:AWKudIfFHg7QIJebnqMcBT+AP5dsxp09gcxCY1Hy7zk=,tag:3xJNNtBCtk1sK8g/1LEotA==,type:str]
    version: 3.13.3
