apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: paperless-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./paperless-db-credentials.enc.yaml
  - ./paperless-config.enc.yaml
