apiVersion: v1
kind: Secret
metadata:
    name: paperless-db-credentials
    namespace: paperless
stringData:
    password: ENC[AES256_GCM,data:za51ZBncXiCZ2J1+Mn9aH1TQ9EaL4HVJNI/WsWlI,iv:LyY9k1iNQyb5BqA0zhG8ckeRcd3fYvWIPJRbwvP/V+Y=,tag:9ybabqFj1B8i3L0qlkxrUg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdUptVDh2WEtOSlFjVFhv
            K3VmdUV1Mk9lbEhDSnhoRExtNW85K0NPQkhJCjNEYWo4d2dvU3JQQzh0TEFvY0VB
            RVdxcHN3bUdhVkFxdWQzaWdyclQ2K2cKLS0tIGJkZ3dsMklNM1czejNObE1aZmJV
            QktTSDZ4OC9NNVNOdGhTdFV2TUNSbUUKGxfSajDsKyYITp8xF752EW/X64No0GCX
            ZNrxlnb8kxI9Rr9RrN4X/nhTLWwrMVEfRgaedkkcpBYKy+95am0lDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tygf3cppgemsa5h93gwyk2ucg55n48ernr8afvpul6uy7pek7sjscavun5
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-08-29T16:07:51Z"
    mac: ENC[AES256_GCM,data:2CcdPUy6u9FzXpXq1MAuDRdg8bqcoCCzyckjwbd5qHVjMqOw8trY4yd+/62qOFU+4nLRuYTrIHmguLjFHYOnVmoTq189f8ERguwqOfSI4YNX8HGFxg1f8wZXp1f+hf4z28eyFQMEXBHckYqx3dKOD1B/P75Tg+9kXKe+5jiDQFM=,iv:oUYCa6DBtUV5ELqckw4Xp1PzofvExopA8dsk3dGTdY8=,tag:xMwiE81RVfaB2LBBKk1/wA==,type:str]
    version: 3.13.3
