apiVersion: v1
kind: Secret
metadata:
    name: actual-oidc-credentials
    namespace: actual
stringData:
    client-secret: ENC[AES256_GCM,data:q09cs7HXwPwLm6fXV1i+HevTrLka1kAW449KmV3Vqm4=,iv:5GUqP/45FUqGWwCiZ8joDFLDV5wp1C7Rn6BN0mmxvm0=,tag:rPTaZIpHrG5WbCDGD2Rl0A==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4c3c4RlFtTVFzME5FeXJH
            UHI5ZHdEbm83MDZadnJjZTVkZ3g3NDIzSkJ3CjFkeUlHR2dxYlczWXRMZGJ2UFlW
            SVA1TFVpdFIxUHFQNlMzZWxMODV2MEEKLS0tIFQybXhhcnJjOXNtcFZGNjZjR0Vq
            a0hTTzkzYk41TEp1UG1MQnRCbjM4UWMKEi+IqTHVlkDRsprKfJvqedkSi+JjmjPy
            Idela73eH63ekkyk3dMdpEn0NrYPAnRH+VzJFY59wQ0E7JqJKqfuFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tygf3cppgemsa5h93gwyk2ucg55n48ernr8afvpul6uy7pek7sjscavun5
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-08-29T16:07:50Z"
    mac: ENC[AES256_GCM,data:FK6YFiwaqycNXZKrXXMYjUUuMvRtS+x93YrreSVQ4SVWU9D+vXXFwI45Aveq8ke4jVVhoUo7yO0mhAoqe0cmKj3rp/JYkbyAnZfy/tEqZgz9c29t4f5C6rJkZetXIhIdWkbZO/hjovzscjHQWwfq9j4PlzrdmMqAzs5qusvroVI=,iv:pooQAGPIDsL3UiEYUpTcvvlGLN0/Q82LDRE8+zwRg5k=,tag:jNa9IJse8CW+l8F8K3rn0Q==,type:str]
    version: 3.13.3
