apiVersion: v1
kind: Secret
metadata:
    name: immich-config
    namespace: immich
stringData:
    immich-config.yaml: ENC[AES256_GCM,data:MpYtYoKenpMD18buLNoDgbckoo7aDAuYjrhMakX6gcgrKgb6TLdzay/aLvNCSQ848jG3o/pPcnO5O7Ezac/MhVa2pfAHgyKqE167+WOY0pse2s6PeNSBv1hmn9/kvvWra3czScgwCkL58cIQMh7hXl7IcOGgYaXddCKNaeKqCeDHO3UIGrjFn2A6QSoqopz2zxVwxr17YIjr00To3u9IzWzrreXma/Kxml50lTNx7vLnV3rx/ZYN7Rry4UIozpBHTNmHe0qdn1StD0s7vIdGFUGnzMuITsYJEtgUEM6KuO3ld3iSd2qSrK+MJnGgVf8CO/xQJ4vKzwiYLg==,iv:bptQHg8yhHfCyAJJo4uPAUkJhrVQapCi8PAX4lzaEfo=,tag:MI6IG822mYBGgpEZS+0Y2w==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQak04M0xNMm1yQUJLdXZE
            QnhnR2ZhM014OHE4VGhEZ2h0WUNaMGYwR21FCkJBSlNPRW91MlFFZ1Azd1FnMXBO
            azZMWW9KZkY5djNJOXhtYUx1cnFXTm8KLS0tIE12K2JDaDlDZ1BwdGRITXFoTUh1
            UWlsVHdXazdZeTRWSlB3TFZHRmFUV2MKUFodRZxNkbcW1roFYo0+I8otStFPwmRP
            mNHPpvGLwyfMdmIVnK9kF0I1J9rW/dCcn7vgoJ9ul7w/zKZMhEqKIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tygf3cppgemsa5h93gwyk2ucg55n48ernr8afvpul6uy7pek7sjscavun5
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-08-29T05:12:22Z"
    mac: ENC[AES256_GCM,data:PgPfdtwiyP/5NPubd/BA1Md8bD5QXU9Zf7tR1h62uGdonMddJ3MiIlme4CjmsZRbqUcHIQN7Lhg7ewTiSyf9q48tHL/abmmL69LuMPMEPBbmA9HYmE9ST8AbQDN92D7Gd9ONTDCwiHXYldddCPaG7QfDUgQiiKXpum0bMHrEzXU=,iv:50Hl0XrUMvntzd+Sxu+m9/OekpAcygGQoSmS1NJDwn0=,tag:3H50cROxbBWcx9p60G1q9Q==,type:str]
    version: 3.13.3
