apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - env-values.yaml

replacements:
  - source:
      kind: ConfigMap
      name: env-values
      fieldPath: data.app-hostname
    targets:
      - select:
          kind: Ingress
        fieldPaths:
          - spec.rules.0.host
          - spec.tls.0.hosts.0
      - select:
          kind: Deployment
          name: lk-jwt-service
        fieldPaths:
          - spec.template.spec.containers.0.env.[name=LIVEKIT_URL].value
        options:
          delimiter: "/"
          index: 2
  - source:
      kind: ConfigMap
      name: env-values
      fieldPath: data.domain-name
    targets:
      - select:
          kind: Deployment
          name: lk-jwt-service
        fieldPaths:
          - spec.template.spec.containers.0.env.[name=LIVEKIT_FULL_ACCESS_HOMESERVERS].value
  - source:
      kind: ConfigMap
      name: env-values
      fieldPath: data.livekit-udp-ip
    targets:
      - select:
          kind: Service
          name: livekit-media
        fieldPaths:
          - metadata.annotations.metallb\.universe\.tf/loadBalancerIPs
      - select:
          kind: Secret
          name: livekit-config
        fieldPaths:
          - stringData.livekit\.yaml
        options:
          delimiter: '"'
          index: 1
