apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-config
    namespace: vaultwarden
stringData:
    admin-token: ENC[AES256_GCM,data:9WglyZ9vpQ7Fo7+laXTEGOKieZo5LccdxQhdcPDhWwZG/SjJ5WQ5M5TvTVOHHeGJCjABCvJ71LNb2JEQfrgg,iv:qGqeAvLmFcfc5h31JrPKhCCs7coRMJccmDUzNjMRoao=,tag:G89UQGABdHDZbmBO3ytz7w==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUElhSUhXQzAvd2pwWnJC
            OEM2M010bUhSc29Wd0kyRUZ0QUtLRERyN2xzCnRBa2xRS001UmFFdjQyMlEza2Jp
            UEJYNGlIZWpXQ0RaR0FoUWVScmtneTQKLS0tIDRPcjJsSVp6V0tmLzRPWWNESkM2
            YUhZaVJXcXRpMXVFR0tjSG1FblQzVmsKzOPBglf05TSR4uZOFSknHQkHKMQMKaJc
            6AQkVwEMjMS+Yp8FFTOkIlcs5/uAbjZ2NRzu2t836dP4x1450FCoJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tygf3cppgemsa5h93gwyk2ucg55n48ernr8afvpul6uy7pek7sjscavun5
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-08-29T21:22:26Z"
    mac: ENC[AES256_GCM,data:bePpHg5IyfxN805EsybTo9iT7AWTwEzh4JY1uoAY/AtGddupO7Ll5GXoXWg6kV92f2sSOAYRFJjNnWcuQJOkUjaxmFF9HoH2rJH0DHdSw1VeQvyPx5OSbPGIvmyrbW5m4QbKDUcPvMf02k9nPFO2jaHz3ROZw7tk/0RMcN+Km+A=,iv:s3tQvIHG7K/G/C4jMkcfTpHtWkej5BXwoB2cRm7UodQ=,tag:MIXUwe9PqDWHGiCEGW7nxw==,type:str]
    version: 3.13.3
