apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - env-values.yaml

replacements:
  - source:
      kind: ConfigMap
      name: env-values
      fieldPath: data.app-hostname
    targets:
      - select:
          kind: Ingress
        fieldPaths:
          - spec.rules.0.host
          - spec.tls.0.hosts.0
  - source:
      kind: ConfigMap
      name: env-values
      fieldPath: data.keycloak-hostname
    targets:
      - select:
          kind: Secret
          name: immich-config
        fieldPaths:
          - stringData.immich-config\.yaml
        options:
          delimiter: "/"
          index: 2
  - source:
      kind: ConfigMap
      name: env-values
      fieldPath: data.storage-class-ceph
    targets:
      - select:
          kind: StatefulSet
        fieldPaths:
          - spec.volumeClaimTemplates.0.spec.storageClassName
  - source:
      kind: ConfigMap
      name: env-values
      fieldPath: data.storage-class-nfs
    targets:
      - select:
          kind: PersistentVolumeClaim
        fieldPaths:
          - spec.storageClassName
