apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: vikunja-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./vikunja-db-credentials.enc.yaml
  - ./vikunja-config.enc.yaml
