apiVersion: v1
kind: Secret
metadata:
    name: vikunja-db-credentials
    namespace: vikunja
stringData:
    password: ENC[AES256_GCM,data:QNY+41EsojHy4ZGTEIb+sXB9ST3Tbh5FOXs6hpXkQqU=,iv:Oc6JkDdyVUQs06EPpZ8LnPzXNjY7LYFuEsk+KyFmdYk=,tag:XoJ3qIl2Hhm+PuDqpedbYw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtblFGOUFNaFkyOHhzZUFG
            WncrOXVPNzc1d2tLMmpXcVg5dithRFd2K3h3ClZUQ2ZkcVBCZzlRVllCTGcyUTF5
            YUVUMDRzd3VyeWZmNmZsNW16K1BrMEkKLS0tIHFXd3ltaFZLSVQreG9VYUZ6UkVT
            WjM0eVMveGM5UG45dStNcHV0cmVHbVEKfZ4RKmsYrWNUbKXQVqVSbNyk+IcUTRkP
            xV9xlQoksGW7GFHz2ngtVEupNR4SAF8WIzmn6e7sx/egr9YKChAC8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tygf3cppgemsa5h93gwyk2ucg55n48ernr8afvpul6uy7pek7sjscavun5
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-09-01T03:17:58Z"
    mac: ENC[AES256_GCM,data:oy5MpwpbgrgnKMJp77TmvTxVTUB+fyIFaVGnA+L/3yGzqARAE5k9x9SbbEmhk6PQt6Gn0f7TPHsJIsbFXB8MQzN9GVOrAGJ47GWDoVgucI7mE9YQHYNfD+dcuy7XO8CgKjp9/xSRebD5KxlFNFkl4G5KRK3/j+9fLbAXyMezCM0=,iv:D7WR+UXjrkXxUg2O7eus9g7pMQCir5m64vwQvn9kTmc=,tag:M6TMRSDS2Fg4pBQbr0w2mQ==,type:str]
    version: 3.13.3
