apiVersion: v1
kind: Secret
metadata:
    name: paperless-config
    namespace: paperless
stringData:
    secret-key: ENC[AES256_GCM,data:eU7oaURR9wzqBB7dtqu5jabpLqtx8gozGCcN5AhypmulP033dKJ9ap3S/BGaW00aVhERXbe7A8iLODNHg5Q=,iv:ZRWXqaSnCI57r6wOhushdLbgI9MgkXokG4IpQ8LYk3E=,tag:eRQF+WudIoIW5t3Hzu6ZvQ==,type:str]
    admin-password: ENC[AES256_GCM,data:vcVXmwjUToFvB3kUHElUFZieeE/jWXjRGqXLVtBkqA==,iv:1l20L8rCVgVpn2xErCLzkCiChTXOWQy9t4rk8czmgx4=,tag:dvvkeJYLoUl95paSFCkW/g==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqN0lqT0hzbncxeWxaeXJn
            eHlBU1BMeUwvWGxtcDF5RjduNTc5REp2U1dnClNFN3gyMGdudTZHRUJGeXA1S1FD
            UmJDTXJwbmRGWGpLSVBRdTAxbEJZaGMKLS0tIEpuVWtscjZOKzlVZlhLbmNPMlor
            eG5EZ2E5MEN2ZTdxQ0djMDhpeU9ZVWMK4H8630V4uzXMe+dcwRBUzjt8CJ0w1Jyk
            B9sH1qdhXpn/h9EFUom5u/sOgUCkloZW250JCxozjwkbV2mUPxrtGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tygf3cppgemsa5h93gwyk2ucg55n48ernr8afvpul6uy7pek7sjscavun5
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-08-29T21:24:09Z"
    mac: ENC[AES256_GCM,data:0vYUVy5YBhAXGfUgcLD3LMU7Zx1SBopn91N/1azbKOtOGPQEgoNVN5V5g5S3Gg1UYatmPcXdvERQh5HYdCUzBq5gDgcYxbJA9+GLqlu1JwEdj7Ppox3zuS3btoStImDbZuYt0Lwa0mIQZTdEuT589DXpFpc7QHqHdQ3BZWFMyKQ=,iv:zspMn0o/Bq/UDz+S+8QpDYlNR6tgYdn4e/OgS2Rxx40=,tag:jIiRqFgdjlEM77wlo4WcSw==,type:str]
    version: 3.13.3
