apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - metallb-ipaddresspool.yaml
  - metallb-l2advertisement.yaml
  - keycloak-secrets-rbac.yaml
  - keycloak-secrets-clusterstore.yaml

generators:
  - ksops-generator.yaml
