apiVersion: v1
kind: Secret
metadata:
    name: bazarr-oauth2-proxy-cookie-secret
    namespace: arr-stack
stringData:
    cookie-secret: ENC[AES256_GCM,data://XJnohKjCyTS/ZX+g7Wi8VWDfNCydf0lshK4AcYBiE=,iv:MO8s34HoIzd1KOBaf3nnNxwLmV0w1RlY5uNdROM9T4I=,tag:CVi+fdeVlkCrmZ0fYJlNnQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbStwMkM4WERIM0lpbVNh
            MG9sWVluLy9qWGZqR3VjQ3ZxUldES2FScTBRCjRFUTgxOW9xczFQMjlIYXNzejRa
            cGhna25rUW9HQVJWNVVxUTlOVWtuN2sKLS0tIDc2SFYrU0U1UVhPZWdBdFA4QVdK
            UHNGUVB4S0UvcitNczYxOS9GMUdHTm8K4OmcnAXtXizFg8fqOnunQNllCHYOtkWP
            38x77wUi2pOoURdaFc3zurJZtEUE0IWsLodyczWyoOmdgWRRKuYoiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tygf3cppgemsa5h93gwyk2ucg55n48ernr8afvpul6uy7pek7sjscavun5
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-09-13T23:12:01Z"
    mac: ENC[AES256_GCM,data:yVawkN/n1IPL3cVVqkbnY5SaydjfYlBOTryJ7/1WbtAIbWubussC1Fcjs9C50KcLg4SuS9gMTh24uIAsOLRZAPHqu1a6TNYAefUKyDShPG/41GHU846Ys8Jqmf4trMxmm2GtwnnjUOcLTlqo/iEg+91fqRv1X0vB8z+m7GaOpDY=,iv:U/hg/eDg9s4f+QlsK0gplEw60kqWXwF+c0pKTIDLbFs=,tag:4nOwQOb3Z4pyR1xNM9nN6w==,type:str]
    version: 3.13.3
