apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - media-rw-pv.yaml
  - network-policies.yaml
  - sonarr.yaml
  - sonarr-oauth2-proxy.yaml
  - radarr.yaml
  - radarr-oauth2-proxy.yaml
  - prowlarr.yaml
  - prowlarr-oauth2-proxy.yaml
  - byparr.yaml
  - bazarr.yaml
  - bazarr-oauth2-proxy.yaml
  - tdarr.yaml
  - tdarr-oauth2-proxy.yaml

generators:
  - ksops-generator.yaml
