apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-oauth2-proxy-cookie-secret
    namespace: arr-stack
stringData:
    cookie-secret: ENC[AES256_GCM,data:CSCEA+sQVfujZkPFxgLKtIJCRS43j6us6xFU4gTB2f4=,iv:1MUSSHebG2oKDxzU3Rz8V6ATj3AI1CVDKfZJP0TFSAA=,tag:RnBvcUruIOP6dIm5EYp7fw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMREw0R2NpNVNMbGpyM0FS
            RFBIYzFWNjRqSHdsU1NueXprQ3A1dm4rMVJJCkxlcy9YSHVGYm4rVGdhdXMyWkd2
            OHFWcCtpZS9zM2RGVDFWVnBYOVhtdG8KLS0tIEVCNlJpTWl2OE5IdnVudmlGYzBt
            cTNzNmdnQ0lqSy9rRUU5N0diMFJuTTAKmGFYkCdcpV/Ju7/BwCxJ35KeQ9zTJjaH
            nChdMffpnHIKV26Ip+5/mMQzCC3gQkaLK6HtXXwFZID2XVPfj3uTgg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tygf3cppgemsa5h93gwyk2ucg55n48ernr8afvpul6uy7pek7sjscavun5
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-09-11T18:06:20Z"
    mac: ENC[AES256_GCM,data:eO1T2pRoWfava9Xp8S976whls+r9UJM4+1fmSjHa6k3rChPLxOu5kdU7hhbJb7TGmtCuxHF+T+rU2Ye1m7NosCqDFC7N6duiYIho21AHjRIzMas56L9rKk+XmxUaV7QzlO0Ka8mBcAOjUnZeR8KTlRI/xUeqHOyJXpUh37PeRO4=,iv:0v+r3TEyWy8Dt60NrhaAyEZy4NFMAmDOVEPikoZ25yk=,tag:VxeSGHnXGl2FiohccELnfA==,type:str]
    version: 3.13.3
