apiVersion: v1
kind: Secret
metadata:
    name: radarr-oauth2-proxy-cookie-secret
    namespace: arr-stack
stringData:
    cookie-secret: ENC[AES256_GCM,data:UEoRCPb+k/G5yCcKtljtVy2V/hTc/Xqw4sTJD3nIBGk=,iv:qL2r505FdywAtoTvtO7Nqo4Yqt2hnRVnMIXqZfafwhY=,tag:ixT4Thtv4vnucpgPWuKEYQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NWkzN21iNnBZVjJrU3Vw
            WEFIWXZIVjZGQ0VrazFVOCsyL0xHZktvR0dFCkpvT1VmblB3QWUrS1FLQlc4dlps
            bUVCWi9XSVVRZHpweXp1M1p0Q3FtWGMKLS0tIFZaa3d5WFlmU3NLdFd0djJJWEhJ
            bDNSenNXd1J2NnFINDlmbGgvc1RzR00K4DLLQ3xQIdrpTo/Jkf1u13s//C6TgtVh
            GYFZgfTm5E6vlInH4Uitni3KWPj4baxjIgxkEtJNkoNotC5La9X+Bw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tygf3cppgemsa5h93gwyk2ucg55n48ernr8afvpul6uy7pek7sjscavun5
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-09-11T18:06:20Z"
    mac: ENC[AES256_GCM,data:WGwejHQv6Na6HSk3Vnx5Tqqj5OZmRwrnVutV1Wtz3pVLws5XiyKHqy98KJ4WOEg2OCIaInrvQaJrhNhwco+JPpWyGn4KzM55rCgOAGH/D8b8pFgThwWSQlGdyMk6TZNoFIF5bayvwm3i1zXPCQS4sW5mnit6wTuqQz0ogBqkUSw=,iv:6bqPnY94veGl5GRb0rOHD8ptigTQuu0qip9atKQ7xVU=,tag:f+Hue2glpi2MxfcSPlMaRg==,type:str]
    version: 3.13.3
