apiVersion: v1
kind: Secret
metadata:
    name: sonarr-oauth2-proxy-cookie-secret
    namespace: arr-stack
stringData:
    cookie-secret: ENC[AES256_GCM,data:iN176MR0em8XSApDS6/hPYm8k/GE/klTJQfo+P3iLsk=,iv:3DU4nGPbmPW+A4K6P9nFcaPgQsQOtpatDi9B9pzKf3w=,tag:SERpj2ulum697xzi8mqAug==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnV09HVW9QdUZXYXFDc1FN
            NG5TNldVYXlsOEl4NkxPYit4UitEd3F5dVg4CkZ6UFZTK1NLdGZUQW5tV2xjbHVh
            RitzUE15aW1HRkhJTEJKYnh1ayt3ZkUKLS0tIDVUYzdPaWxXMEFMeXExN2hmVVVi
            TFcwN2ZxdE50QWNwYm5CTEdwcmkvcjAKY8QpnsUi7UThR/ydo1PNZNikKw8PXLX/
            SKlJ6q38F8bGrRVSSzROQkTlxOaftrJ69vQytJRPPRkBHUvUg8fWvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tygf3cppgemsa5h93gwyk2ucg55n48ernr8afvpul6uy7pek7sjscavun5
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-09-11T18:06:20Z"
    mac: ENC[AES256_GCM,data:XLbPp8O8jZOc3gfu56bCr1l+tx+cBfYKaFVjorsAo9rSehG+ioWu4yIRMEoa8eVetsK0msCqjpvwNjbHHgsp/2QE1ErYrLw2iZhhP39a/bh4J9cY7h9f4xQVyHDye1OaezyfP3kJ3DTTqzWGDJngRPZdkVcDciDKgOvDiQOlkKE=,iv:Ij19VDTKEONPBWnlwnylO+jSonc9/e0kQRx76wTFbAs=,tag:aFy8+zb5WEnoaYcSHoG/lA==,type:str]
    version: 3.13.3
