apiVersion: v1
kind: Secret
metadata:
    name: tdarr-oauth2-proxy-cookie-secret
    namespace: arr-stack
stringData:
    cookie-secret: ENC[AES256_GCM,data:05Ke2UOruzxzraRcHnVkD5sYWQQQV2uVR8DkIuVH5MM=,iv:Vd36vwOEezft1HxP5siFiiIDlpaUNoIaK0gDQnAerkw=,tag:75/3Nb6dj6xuE4ON3oiLAg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvS0YxSEJCU2lEZ2QrdjRY
            VXBDeUlQOXFwOVhFcEJkSVd1aGJTRUwzQVJZCmF3a2NXY3dWek1WWEtDbDN6Yklv
            bkJ0akYzV3FCS2tNaDFXaC9wSysxZ1EKLS0tIEFPN2w4a2Y2TERYZk1QTTgxbGJJ
            T0RFY09MeU9qbUl3dDZESEtjeFJWb3MKcxrbgFNVRXRwolSjRmMXzjQ/WtwU4HIK
            GJ0uAlrrO+niEOVCF9vl9KwJYuSnLqnISfRcaREuFQr3nL6pzqy69Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tygf3cppgemsa5h93gwyk2ucg55n48ernr8afvpul6uy7pek7sjscavun5
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-09-13T23:12:50Z"
    mac: ENC[AES256_GCM,data:m0yWWyjVVGUwZ254CRdpVr2GqYC3StcnlT6qR/b6QkxzymgW+aAAxsW+7KN65FlXzQ0nlK7RO96d82eCapKyRkKs8//Hjnk7+AgIfKJH59lEUgb/iy4mUuVaBFAaaQUJFhe12tZfUHUK7yvwqwKMh78VNZudafK4M5+z1IjGx3s=,iv:Uc3TgD4+rYCOYfcYklNWfbrdDuHTGP5DHZVSTMCDGN0=,tag:nmbSOXtIpjTUzF4v1zEYXQ==,type:str]
    version: 3.13.3
