apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: media-requests-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./seerr-oauth2-proxy-cookie-secret.enc.yaml
