apiVersion: v1
kind: Secret
metadata:
    name: seerr-oauth2-proxy-cookie-secret
    namespace: media-requests
stringData:
    cookie-secret: ENC[AES256_GCM,data:cJ3jAu966kCSjjtrX5B9K+i4IJ/ukapky3kI+rwXPvE=,iv:yPe1qPYOSnIvzVg/vv3ZNk9beSMuu8E4gJs/rSWgDCI=,tag:264ddM9M2qkRZ3U2illQJg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aGhkWCswelpuVC9oVzFL
            VEFtd1FFcEdHUTNmMlJIUGZucVgxd0RyVHg4Ck5PajhVV3Q5UkRiYUpRSlB4VmhY
            VG9OYlcwcmFhUGFBd0JiM2lqZ1lBd2MKLS0tIDFCUnhISzR6Q3ZQYTZGb0FvYUhp
            cGhaNXloVXFhOGR5YXlRaG9EMm4veDgKHXN7XVQ+E2DNHdQLiZnNCw47TitUZwFO
            db6lhwA6d1tACUWHQsHfaED43QAqVEbHvFd1509VnSkG1APCYspXNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tygf3cppgemsa5h93gwyk2ucg55n48ernr8afvpul6uy7pek7sjscavun5
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-09-13T23:42:07Z"
    mac: ENC[AES256_GCM,data:vc2eH2o+kOGdc6gmdydQVQ4vUwc6tx31+100YtjjcZGwxplyQ++NNo/4oN+BZgplCiNdVPFg/nS2ObPwCOK8esf3wASnCb0CHKFtBhf8VtulZhu4HjLzZUTCgmPAlBU5lcxD7lbxjxcoAdLcTF4YArrGnQ/hm5QXyu8rFToTBZI=,iv:HfuFsRRwvrGPzYUDyDPX0OumkIIMrt9RpxqkKTJ8f18=,tag:R3t4dM3FJUSbx6btQvQhVg==,type:str]
    version: 3.13.3
