apiVersion: v1
kind: Secret
metadata:
    name: immich-db-credentials
    namespace: immich
stringData:
    password: ENC[AES256_GCM,data:FeRjcet/IioeaXGN4ThktktZrQTGAV42HI9qruO+,iv:2+6nyNHE0X2ipSM3Rqb9TVC/I4mvswFf2n5Q5SX/TVM=,tag:Ul/ObIYGP2GIcaAvBb+p/Q==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTnNQVlJNWGpIM2NnSm1a
            eTZmU2xZRmQ0TkF5U1JidjdFMkNreHpJbFNZClJxNVVidkFVaFB2U2poSXV6NFhH
            bWhNQlJ3ZmMvbUoyTE5zRjQrNUxrRHcKLS0tIDQwMWZzSGhPZFRoOWRLR0EyTHpv
            YlpMQnpwWnJwc0hxSGV5L3VEYVpQV00KkVRNls9hmdygZhj6z2ZpTiP3nAe/IdPO
            HK6FhJ8k4X8tc/Q3iOGkNQXkPtWNg3Oq512hOoy0ZAZ4bWhRtX41tA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tygf3cppgemsa5h93gwyk2ucg55n48ernr8afvpul6uy7pek7sjscavun5
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-08-29T05:12:22Z"
    mac: ENC[AES256_GCM,data:2iJ8cxiC9Kx46TGGEWtF5vo1IT6BBarEwAKgckgjvG/BOhTMZvDZ5ZM0MurRoSL6bgoIG1k4bcg2nbWz+4PCIxgyiN3/ETQHRPlPBjXKV13RglU9R0D6+zFGeyJZsNF0/+blsDSn6WJGj481JEUESwZgbo3dorQIKJGt63s5gXo=,iv:t+AHfJpXms6yZfN5p6uz8WkNtB3LqpCVq5C/knhYawE=,tag:1eacnZeJi0MMY4Twaq5oIQ==,type:str]
    version: 3.13.3
