apiVersion: v1
kind: Secret
metadata:
    name: immich-config
    namespace: immich
stringData:
    immich-config.yaml: ENC[AES256_GCM,data:eGE4nlevW251YIqGfc4MmEcBuus/TK0x+P+0yXdfikjgch3oo6YLspHjzbgcfu3rq4iggM57yuO3XebIEP0d4EZKbfc/tEsJNMQoL5Q7+q8aC86A6zkblNucKj6NiqjZKgO6ahPDCLgFcVdy2p/pnD0ghXb49h1b75Yx1lf2/4oBUUI+Arzbrkb+bjuuMorIOQXG2/llIywIkuc5Pfoy1AWI5FXuxYRME9O8njEuVUvBKkH6T39uuA3agUbch0N3bFSSAgWC6S5M/WFagYkIn3woICqd7/tzu9ZFIQi0UcvtZltcfJmytiCXJ8vfltIAZCbhn8fNa6R3G4uKKOPQkJ9XXmuSUHj1VL6YnUr8bjcCFBE/zkR3VTdMLUNZP10+9I9dEH7MBmySAKiyfh7G,iv:zIbFp25t6OHeFHSUK3eb22f7PSEQBMrZDC5q4hhclIE=,tag:zVeXRQclUMVDgu7JgVZTlg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdnBucnEyeXV5V0ZCNjdG
            c1BiaWJmSEt3aDZZV3ZQaWQvV0dsdHdDbTJZCkVtU2tvSUhpTWx6RVJlclRCTm5m
            OHpaT3VqRnVmY1dvRHc3SmRRU2kybGMKLS0tIENVZ1M0bVZERDJldFNFRUJMaHk3
            T1BxNWNFUXMxeitmYUpJUm1ySGpzdlkKXP+pO2NUPBscz56+K98iyp4/Rwsh6B53
            B0drwB7iyzPVwHjXuB+zVN4fU8us7F4ELTuMxPC7GHsDiPKGbQTiGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tygf3cppgemsa5h93gwyk2ucg55n48ernr8afvpul6uy7pek7sjscavun5
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-08-29T20:29:38Z"
    mac: ENC[AES256_GCM,data:5wzrCfD+A8NVAyKduX8p7JymAaGK1EQueb8owYdieBWUULy4MJju+w7wtrWlTxswMLAG/U9EiYpyFvuJgbxD4cxH31jSBC1USAsEk8atDutojUA6jYTXfBJv3+gM1shwhTSnisJR8f1mZorOEnHEIsMpTlOAjTfYgKS3sgaxEcY=,iv:9u1WZu/Bpi6iRxldpBOJ6E2jsC7sBsLpYZFXJ2hwgeE=,tag:U2gfMzwau9cse7XqqrkpZQ==,type:str]
    version: 3.13.3
