apiVersion: v1
kind: Secret
metadata:
    name: changedetection-cookie-secret
    namespace: changedetection
stringData:
    cookie-secret: ENC[AES256_GCM,data:MZSlpvM3n7Oos46bcgDj7gMGJWqe3bdgXoh1j6C0tkw=,iv:tVC14Kj5CFcj1kWlerfvnG7vNA1D2tt3eVPXPkYi/+s=,tag:b5u3wjkXR2FQv0jgjDzUpw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlOFd1VVV6bHdPRXpncnZE
            WmpGUm1PTnlvdXd1b3pZaGQxTzc4TWZTbWlFCnE5ck9CcmJ3eTJiVUk0SmlITmJD
            VnhrMy94Ylk2cnJzSW0ybkxIcVlPZkEKLS0tIDlDMUhYZjJVaEczM2hXVXJVMEly
            RmJGUUdEY0MzU1Z2RytuUGVwNmZySVkKRm3J+pXvJoKHAiPRE+wBLt8kwk/gBgH1
            CXrZqwNlnpB/cFTfZpIta3nk6/tW0QGcKIKoFeFGJ++hw1bcyb7kog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tygf3cppgemsa5h93gwyk2ucg55n48ernr8afvpul6uy7pek7sjscavun5
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-08-29T21:23:30Z"
    mac: ENC[AES256_GCM,data:iLPYC0eTcMyB28SXg+ACgVYFK1y7LAQz2rCLqmdZ1b+C1mubaoJ6KgFnnYLd5TTPLS3lzflPpeUAGjrI/niJ//0U6EruTfScWmtIDn6bWyp0jUbpLovW6cLCiWXoUoVGWZwPj4FjjMX8Ima5Q4Qa2tsZwAH5BrgaU7vxkLuepMo=,iv:gLOPCNy6cyV4GwHzAXtxbqNAITAZRIBhBfe/On0IgOY=,tag:72Nm1s7n7ALkKMC1HC5IKw==,type:str]
    version: 3.13.3
