apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: changedetection-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./changedetection-oauth2-proxy-credentials.enc.yaml
