apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - data-pvc.yaml
  - network-policies.yaml
  - changedetection.yaml
  - oauth2-proxy.yaml
  - changedetection-oauth2-proxy-credentials.yaml

generators:
  - ksops-generator.yaml
