apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: matrix-mas-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./mas-db-credentials.enc.yaml
  - ./mas-secrets.enc.yaml
