apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres.yaml
  - mas-config.yaml
  - mas-secrets-externalsecret.yaml
  - mas.yaml
  - network-policies.yaml

generators:
  - ksops-generator.yaml
