apiVersion: v1
kind: Secret
metadata:
    name: mas-db-credentials
    namespace: matrix-mas
stringData:
    password: ENC[AES256_GCM,data:vLcP3+WTqTqSMxfQ5YQI1nlCja9kso4cFiANhjmDakQ=,iv:v0kA4+7Ynvg8XJxSmKq9D4vzECq8ou3Y0K2bthPmqdI=,tag:/6IwRntJrncLVrMddQ8m6Q==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1TjVvUUczcWJEUFBVamlw
            VzFJUnJRZCtLMll4Snk5RGpjQlZwNDYxaVNVCmZpeHF4YjZYQVpZbXVqZVBjTHZv
            T2QxR1pSa1ZLMVd0NHBmakhlOWtPU00KLS0tIDZGVHlQR3BSaDlLazZpZk81NThl
            cTBUVEFhMFFNSnVaRnlMankxK1ZGeUkKnDEn/lydDGqBfg9EFHYYSx3p0Jn7lhfa
            iOJqQSOMO1Ka/YbBJcbCMYi1L19lrS+P1TiPJbhho1Ra0qgOjzp8/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tygf3cppgemsa5h93gwyk2ucg55n48ernr8afvpul6uy7pek7sjscavun5
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-09-02T05:38:38Z"
    mac: ENC[AES256_GCM,data:zjNYGN1KGiFZ3PMfPoCMn6qcwIiWwaSNssZUf19mhkOhcl0hqj/vzezGeyf5e0jMluCvOeQhjldFmz0saOPtqywK3FPBLjFaI485IMVm30T+PnTbBOE0MIQn0LL2IDyl/7dkp3DK62S5iJS2xwEVLiOsA35OySFDeY1oRe9fNSU=,iv:QhiBOUOH9dcAF4r3Qf4gLhsPRWAWpSqLcFnOksgVsbY=,tag:EwCFrX7FQVJdjMev+3J30A==,type:str]
    version: 3.13.3
