apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: matrix-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./matrix-db-credentials.enc.yaml
  - ./matrix-secrets.enc.yaml
