apiVersion: v1
kind: Secret
metadata:
    name: matrix-db-credentials
    namespace: matrix
stringData:
    password: ENC[AES256_GCM,data:wm/nEPiRKJwYgnQ+OYgwYCaciGZOKde0iLJ8Mm33jRcZVimAh9TiMZK8mhY=,iv:lbvKzP441cPwne6vRWIU7LtIXlX+nroNn+uHyYjIN5o=,tag:pKuhIZX+XRGZpUq5iN774w==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ejJyem1PUzFqYmovOGVs
            VWxmcVR5NkZQQ1NwZDNpdlltTXJmT0Q3Smc0CmRETEhXMU5SbXlkZ25SemtwTW42
            ZzhMMjVvV29iQW1MMy9pV0ExWWV4MjQKLS0tIFhzRGYzMVk3a2hoNjMyamthR1Nu
            Z2dEbVpOSmhpTU5EbWV4YS9DZDlFd0UK+sXwmUlEbzfoc9tQvfT4j9mdBIjIhMlA
            UoIfKt3w6y3MxaRPS631oa9h18PFHraOXhIdGB29Lc+mhoIXoCdDSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tygf3cppgemsa5h93gwyk2ucg55n48ernr8afvpul6uy7pek7sjscavun5
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-09-01T17:43:34Z"
    mac: ENC[AES256_GCM,data:Nb/JR2eaLLelMzNV5yXpDwxEkrDs8c8P3wSlloZZWNASYMqkAV08JsL3trxlrkjCIAIeZCriIFkm/+10DKAqeOHuHesXptFPg+eFXkVmphCfHBgP7Wnt1IJaZ5dDpSd/5bS7jr8GY7IhIc2t4Q4bDe2kFv5WrDhh1d9mxyGFnT8=,iv:qOQXcQmlp+tG0VkJ0ifq4HnYMVfGNadPrN2T/todq7s=,tag:CdjoELiRX/Z2f4ijM3GAwA==,type:str]
    version: 3.13.3
