apiVersion: v1
kind: Secret
metadata:
    name: matrix-secrets
    namespace: matrix
stringData:
    secrets.yaml: ENC[AES256_GCM,data:zZUcUeimTy3OZgLgTzVoZot+pMNTiz5/Un5YYAZ1EJ5gLhqvi11gpLJwfEsueDD2aSThX1FdVJeoyj3WjWl8S3DZ0QXLX+h2Pvl3FKBL4O+yBIsruE6asHegVZOgSeabnjbSKcX51YUpwh8wWbBSYuZoVBSsgWC+C3Glza4c47puk2JubZ5PgBG1eVP4LHTGKisXGnjBITr0PbhtpSMjdbI38hwsxCwClrAdv5e87I7asz/ERStsBFAPwQ2rUDMu+rGTQK8SnvX+py0MrbOE/dHfiud3bx3qdNITLTjZ6CqOz4M8VKYbREUjcDmripWShpdysOO2JVSWqpzsGlBYV266JG/T7VF3LOJ6SrUuSdjTeLMehVGipRnHVAGW/OyBtxu96X3ErIZD6/tfewwaZ5UFPvi3yjFEBKT3SMOfhJgZRVrCCxu46xvzvLK7Jqf+ckDxGZxgQc631SXbHnbczoTnMy5/c4575cCsH+ePT7oLtDuHa6a/KezT/tYLIaHh+5NOvrNN+IkEpC5qt7+4ZSCXdDKiirPUvEWfdAk+jnnDNxU2pT3rDYfSy4zjq2j2vF4Q4jla+gPOWd7DZthHJfcsseVLb/X5g/l+pOUjnEDsxlU=,iv:J9UCMQ3D0qeib80JetLS3Io9H2VcCCBc1YuzJ5smFv0=,tag:lSyzO7LxokhSS63YkxpFHw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPeGxpN0dON3h6ckpsZkhh
            cXUva2YvR0daQ0Rvekk4YThLY3JIUksvQUI0CkwrQStPTGdEOW1vRzJBS1NJRTZZ
            cllkOVF4U2txb1hrYTdWWFhGL3E1V2sKLS0tIEI0dEZ4TDdrNVBCTFBnRVlRTGRK
            YXBIMitvMDRqSk5WbE1DVzQwSnlPKzQKqdimUH8LpY8+0osIOLfnAGqMT5lMHnEx
            S8jphPDdN1xdtPdtoh4D3CoOlplBiKyix8oFQfsOE9Y+fvmbodtcrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tygf3cppgemsa5h93gwyk2ucg55n48ernr8afvpul6uy7pek7sjscavun5
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-09-01T17:43:34Z"
    mac: ENC[AES256_GCM,data:CmHAa6Pbj6GUIF0rLu6rMGEdRFbKb9un1uWlV1SfpfsP5AO0bEpuEKE+/JLERCuOJB0ZA9gaP8jI9PgKGTQC+o/dV0MM72vNhVTjR34U0lTINFs/tFMJ5q9kJQUAIoeN2arxFX7TlBJjoTyHq+igl8lp29qA3eymX2NJkl42WUU=,iv:Qal+RPfP+qdNv104wPs+OSYHAOhkG5c4MpAecZPBVvY=,tag:eQi4svhZoj28MAA4eepVdA==,type:str]
    version: 3.13.3
