apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - env-values.yaml

replacements:
  - source:
      kind: ConfigMap
      name: env-values
      fieldPath: data.app-hostname
    targets:
      - select:
          kind: Ingress
        fieldPaths:
          - spec.rules.0.host
          - spec.tls.0.hosts.0
      - select:
          kind: Deployment
          name: changedetection
        fieldPaths:
          - spec.template.spec.containers.0.env.[name=BASE_URL].value
        options:
          delimiter: "/"
          index: 2
      - select:
          kind: Deployment
          name: oauth2-proxy
        fieldPaths:
          - spec.template.spec.containers.0.args.2
        options:
          delimiter: "/"
          index: 2
      - select:
          kind: Ingress
          name: changedetection
        fieldPaths:
          - metadata.annotations.[nginx.ingress.kubernetes.io/auth-signin]
        options:
          delimiter: "/"
          index: 2
  - source:
      kind: ConfigMap
      name: env-values
      fieldPath: data.keycloak-hostname
    targets:
      - select:
          kind: Deployment
          name: oauth2-proxy
        fieldPaths:
          - spec.template.spec.containers.0.args.1
        options:
          delimiter: "/"
          index: 2
  - source:
      kind: ConfigMap
      name: env-values
      fieldPath: data.storage-class-ceph
    targets:
      - select:
          kind: PersistentVolumeClaim
        fieldPaths:
          - spec.storageClassName
